Vagrant.configure("2")do|config|
  config.vm.box="tp3-b2-centos"
  config.vm.network "private_network", ip: "192.168.2.31"
  config.vm.hostname = "tp3.b2"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", 
  source: "systemd/units/WebServer.service", 
  destination: "/tmp/WebServer.service"

  config.vm.provision "file", 
  source: "systemd/units/backup.service", 
  destination: "/tmp/backup.service"

  config.vm.provision "shell", path: "scripts/script_install.sh"

  config.vm.provision "file", source: "scripts/pre_backup.sh", destination: "/home/backup/backupDir/pre_backup.sh"
  config.vm.provision "file", source: "scripts/backup.sh", destination: "/home/backup/backupDir/backup.sh"
  config.vm.provision "file", source: "scripts/backup_post.sh", destination: "/home/backup/backupDir/backup_post.sh"

config.vm.define :tp3 do |t|
end

config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.name = "tp3.b2"
end

end